// packages/gaudi/src/components/subscriptions/subscription_card/subscription_card.svelte
<script lang="ts">
	import { H3, TextVariant } from "../../../index";

    export let title: string;
    export let price: string;
    export let features: string[];
    export let mainCard: boolean = false;
</script>

<div
	class="w-96 h-96 p-10 rounded-sm border border-stone-300 flex-col justify-center items-center gap-10 inline-flex"
    class:bg-stone-100={mainCard}
    class:bg-white={!mainCard}
>
	<div class="flex-col justify-start items-center gap-4 flex">
        <H3 variant={mainCard ? TextVariant.Terciary : TextVariant.Primary}>{title}</H3>
		<div class="justify-start items-end gap-2.5 inline-flex">
			<div class="text-[#426578] text-2xl font-bold font-['Montserrat'] leading-normal">{price}</div>
			<div class="text-neutral-400 text-base font-normal font-['Montserrat'] leading-normal">
				al año
			</div>
		</div>
	</div>
	<div class="flex-col justify-start items-start gap-5 flex">
        {#each features as feature}
            <div class="justify-start items-center gap-1 inline-flex">
                <div class="w-3.5 h-3.5 px-0.5 py-0.5 justify-center items-center flex"></div>
                <div class="text-neutral-800 text-sm font-normal font-['Montserrat'] leading-none">
                    {feature}
                </div>
            </div>
		{/each}
	</div>
    <slot/>
</div>

// apps/server/src/components/organisms/subscription/subscription-card.tsx
import { Typo } from '@/components/atoms/typographies';
import classNames from 'classnames';
import React from 'react';

interface Props extends React.HTMLAttributes<HTMLDivElement> {
  title: string;
  price: string;
  interval: 'day' | 'week' | 'month' | 'year';
  features: string[];
  mainCard?: boolean;
  children?: React.ReactNode;
};

export const SubscriptionCard: React.FC<Props> = ({
  title,
  price,
  interval,
  features,
  mainCard = false,
  children,
  className,
  ...rest
}) => {
  return (
    <div
      {...rest}
      className={classNames(
        'w-96 h-96 p-10 rounded-sm border border-stone-300 flex-col justify-center items-center gap-6 inline-flex',
        className,
        {
          'bg-stone-100': mainCard,
          'bg-white': !mainCard,
        }
      )}
    >
      <div className="flex-col justify-start items-center gap-4 flex">
        <Typo.H3 className='w-full'>{title}</Typo.H3>
        <div className="justify-start items-end gap-2.5 inline-flex">
          <div className="text-[#426578] text-2xl font-bold font-montserrat leading-normal">
            {price}
          </div>
          <div className="text-neutral-400 text-base font-normal font-montserrat leading-normal">
            {
              {
                day: 'al día',
                week: 'a la semana',
                month: 'al mes',
                year: 'al año',
              }[interval]
            }
          </div>
        </div>
      </div>
      <div className="flex-col justify-start items-start gap-5 flex">
        {features.map((feature, index) => (
          <div key={index} className="justify-start items-center gap-1 inline-flex">
            <div className="w-3.5 h-3.5 px-0.5 py-0.5 justify-center items-center flex"></div>
            <div className="text-neutral-800 text-sm font-normal font-montserrat leading-none">
              {feature}
            </div>
          </div>
        ))}
      </div>
      {children}
    </div>
  );
};
