// packages/gaudi/src/components/common/toggle_button_group/toggle_button_group.svelte
<script lang="ts">
	import { fade } from 'svelte/transition';

	type ButtonOption = {
		id: string;
		label: string;
		sublabel?: string;
	};

	export let options: ButtonOption[] = [];

	export let selected: ButtonOption;
	export let setOption = (option: ButtonOption) => (selected = option);

	$: activeIndex = options.map(option => option.id).indexOf(selected.id);
</script>

<div class="px-1 py-1 bg-stone-100 rounded-full justify-start items-center gap-6 inline-flex">
	<div class="self-stretch justify-start items-center gap-2 flex">
		{#each options as option, index}
			<div class="relative">
				{#if index == activeIndex}
					<div
						transition:fade
						class="absolute left-0 h-full bg-white rounded-full pointer-events-none w-full selected-interval"
						aria-hidden="true"
					></div>
				{/if}

				<button
					class="relative flex text-xs h-8 rounded-full gap-1 transition-colors duration-150 ease-in-out font-['Montserrat'] justify-center items-center mx-2"
					class:text-black={selected.id === option.id}
					class:text-neutral-400={selected.id !== option.id}
					class:font-normal={selected.id !== option.id}
					class:font-bold={selected.id === option.id}
					on:click={() => setOption(option)}
					aria-pressed={selected.id === option.id}
				>
					{option.label}
					{#if option.sublabel}
						<span class="text-slate-600 text-xs font-['Montserrat'] leading-3">{option.sublabel}</span>
					{/if}
				</button>
			</div>
		{/each}
	</div>
</div>

// packages/gaudi/src/common/toggle_button_group/toggle_button_group.tsx
"use client";

import React, { useState } from 'react';
import classNames from 'classnames';

type ButtonOption = {
  id: string;
  label: string;
  sublabel?: string;
};

interface Props {
  options: ButtonOption[];
  selected: string;
  setOption: (option: string) => void;
};

export const ToggleButtonGroup: React.FC<Props> = ({
  options,
  selected,
  setOption,
}) => {
  
  const [activeIndex, setActiveIndex] = useState(
    options.map((option) => option.id).indexOf(selected)
  );

  const handleClick = (option: ButtonOption, index: number) => {
    setOption(option.id);
    setActiveIndex(index);
  };

  return (
    <div className="px-1 py-1 bg-stone-100 rounded-full justify-start items-center gap-6 inline-flex">
      <div className="self-stretch justify-start items-center gap-2 flex">
        {options.map((option, index) => (
          <div className="relative" key={option.id}>
            {index === activeIndex && (
              <div
                className="absolute left-0 h-full bg-white rounded-full pointer-events-none w-full selected-interval"
                aria-hidden="true"
              ></div>
            )}
            <button
              className={classNames(
                'relative flex text-xs h-8 rounded-full gap-1 transition-colors duration-150 ease-in-out font-montserrat justify-center items-center mx-2',
                {
                  'text-black font-bold': selected === option.id,
                  'text-neutral-400 font-normal': selected !== option.id,
                }
              )}
              onClick={() => handleClick(option, index)}
              aria-pressed={selected === option.id}
            >
              {option.label}
              {option.sublabel && (
                <span className="text-slate-600 text-xs font-montserrat leading-3">
                  {option.sublabel}
                </span>
              )}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
