// packages/gaudi/src/components/common/header/header_submenu/header_submenu.svelte
<script lang="ts">
  import type { MenuSection, UserModel } from "hegel";

  export let user: UserModel;
  export let toggleMenu: (changeTo?: boolean) => void;

  export let menuSectionsLoader: (user: UserModel) => [MenuSection];
  const menuSections = menuSectionsLoader(user);
</script>

<div
  class="w-40 bg-white rounded-sm flex-col justify-start items-start inline-flex"
  on:mouseleave={() => toggleMenu(false)}
  role="menu"
  tabindex={7}
>
  {#each menuSections as section, i}
    {#if section.title}
      <div
        class="text-menu-section-title text-xs px-5 py-2.5 font-bold font-['Montserrat'] leading-3"
      >
        {section.title}
      </div>
    {/if}
    {#each section.items as item}
      {@const action = item.action}
      {@const href = item.href}

      <div
        class="h-8 px-5 py-2.5 flex-col justify-start items-start gap-2.5 flex"
      >
        <div class="self-stretch h-3.5 justify-start items-center gap-1 flex">
          {#if action}
            <button
              on:click={() => {
                action();
              }}
              class="text-black text-xs font-normal font-['Montserrat'] leading-3"
            >
              {item.text}
            </button>
          {:else if href}
            <a
              {href}
              class="text-black text-xs font-normal font-['Montserrat'] leading-3"
            >
              {item.text}
            </a>
          {/if}
        </div>
      </div>
    {/each}
    {#if i < menuSections.length - 1}
      <div class="self-stretch h-px border border-[#dadada]"></div>
    {/if}
  {/each}
</div>

// packages/gaudi/src/common/header/header_submenu.tsx
"use client";
import { MenuSection, UserModel } from "hegel";
import React from "react"
import { useState } from "react"

type Args = {
    user: UserModel
    toggleMenu: (changeTo?: boolean) => void
    menuSectionsLoader: (user: UserModel) => [MenuSection]
}
export const HeaderSubmenu = ({
    user,
    toggleMenu,
    menuSectionsLoader
}: Args): JSX.Element => {
    const [menuSections] = useState<MenuSection[]>(menuSectionsLoader(user));

    return (
        <div
            className="w-40 bg-white rounded-sm flex-col justify-start items-start inline-flex"
            onMouseLeave={() => toggleMenu(false)}
            role="menu"
            tabIndex={7}
        >
            {menuSections.map((section, i) => (
                <React.Fragment key={i}>
                    {section.title && (
                        <div className="text-menu-section-title text-xs px-5 py-2.5 font-bold font-montserrat leading-3">
                            {section.title}
                        </div>
                    )}

                    {section.items.map((item, j) => {
                        const action = item.action;
                        const href = item.href;

                        return (
                            <div
                                key={j}
                                className="h-8 px-5 py-2.5 flex-col justify-start items-start gap-2.5 flex"
                            >
                                <div className="self-stretch h-3.5 justify-start items-center gap-1 flex">
                                    {action ? (
                                        <button
                                            onClick={action}
                                            className="text-black text-xs font-normal font-montserrat leading-3"
                                        >
                                            {item.text}
                                        </button>
                                    ) : href ? (
                                        <a
                                            href={href}
                                            className="text-black text-xs font-normal font-montserrat leading-3"
                                        >
                                            {item.text}
                                        </a>
                                    ) : null}
                                </div>
                            </div>
                        );
                    })}

                    {i < menuSections.length - 1 && (
                        <div className="self-stretch h-px border border-[#dadada]"></div>
                    )}
                </React.Fragment>
            ))}
        </div>
    );
};
